[project]
name = "dev-tools"
version = "0.1.0"
description = "Tools for dev tools"
requires-python = ">=3.9"

[project.scripts]
dev-tools = "dev_tools.cli:app"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I","UP"]

[tool.pytest.ini_options]
addopts = "-q" 