name: CI - PowerShell
on: [push, pull_request]
jobs:
  ps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install test tooling
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
      - name: Lint
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path modules/powershell -Recurse -Severity Warning -ReportSummary
      - name: Test
        shell: pwsh
        run: Invoke-Pester -Path modules/powershell -CI