name: CI - Python
on: [push, pull_request]
jobs:
  py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -U pip || true
          pip install ruff black pytest typer || true
      - name: Python syntax check
        run: |
          find modules/python -name "*.py" -exec python -m py_compile {} \; || true
          echo "Python syntax check completed"
      - name: Lint with ruff
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check modules/python || true
          else
            echo "ruff not available, skipping lint"
          fi
      - name: Format check with black
        run: |
          if command -v black >/dev/null 2>&1; then
            black --check --diff modules/python || true
          else
            echo "black not available, skipping format check"
          fi