name: CI - PowerShell
on: [push, pull_request]
jobs:
  ps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install test tooling
        shell: pwsh
        run: |
          try {
            Install-Module Pester -Force -Scope CurrentUser -ErrorAction Stop
            Write-Host "✓ Pester installed successfully"
          } catch {
            Write-Host "⚠ Pester installation failed: $($_.Exception.Message)"
          }
          try {
            Install-Module PSScriptAnalyzer -Force -Scope CurrentUser -ErrorAction Stop  
            Write-Host "✓ PSScriptAnalyzer installed successfully"
          } catch {
            Write-Host "⚠ PSScriptAnalyzer installation failed: $($_.Exception.Message)"
          }
      - name: PowerShell syntax check
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Continue'
          Get-ChildItem -Path modules/powershell -Recurse -Filter "*.ps*" | ForEach-Object {
            try {
              $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content $_.FullName -Raw), [ref]$null)
              Write-Host "✓ $($_.Name) - Syntax OK"
            } catch {
              Write-Host "⚠ $($_.Name) - Syntax issue: $($_.Exception.Message)"
            }
          }
      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          if (Get-Module -ListAvailable PSScriptAnalyzer) {
            try {
              Invoke-ScriptAnalyzer -Path modules/powershell -Recurse -Severity Warning -ReportSummary
            } catch {
              Write-Host "⚠ PSScriptAnalyzer failed: $($_.Exception.Message)"
            }
          } else {
            Write-Host "PSScriptAnalyzer not available, skipping lint"
          }