name: CI - Shell
on: [push, pull_request]
jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shell tools
        run: |
          sudo apt-get update || true
          sudo apt-get install -y shellcheck || true
      - name: Lint shell files
        run: |
          if command -v shellcheck >/dev/null 2>&1; then
            find modules/ -name "*.sh" -o -name "*.zsh" -o -name "*.plugin.zsh" | xargs shellcheck -x || true
          else
            echo "shellcheck not available, skipping lint"
          fi
      - name: Basic syntax check
        run: |
          find modules/ -name "*.sh" -exec bash -n {} \; || true
          echo "Shell syntax check completed"